### model
model_name_or_path: ../Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: pp,MG,caption,MGC
template: llama3
cutoff_len: 1024
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/sft
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: false

### train
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3
lr_scheduler_type: cosine
#warmup_ratio: 0
bf16: true
ddp_timeout: 180000000
include_num_input_tokens_seen: True

### eval
val_size: 0.005
per_device_eval_batch_size: 3
eval_strategy: steps
eval_steps: 1000
